### ISSUE TITLE
How is this gem used?

### ISSUE THREAD

**Issue by dgmstuart** [meganemura/sloc#20]
Hello. I've been looking for a gem like this, but I can't seem to work out how to use it properly

I've tried it on directories:

```
sloc /app
sloc .
```

I've tried it on files:

```
sloc app.rb
sloc functions.pho
```

...But in all cases it just returns a blank line

The usage message says `Usage: sloc [options]`, implying that it takes no arguments at all (or only flag arguments?)

**Comment by meganemura** [comment]
Hi, thanks for reporting issue and interesting in this project.
This behavior was bug and was fixed in #21 and released as v0.1.3 (#22).

This project is currently in active development.
So, many features were not implemented.

If you want some features, please feel free to create issues.

**Comment by meganemura** [comment]
Oops. I forgot to tell you about how to use this.
Updated usage in [README.md](https://github.com/meganemura/sloc/blob/master/README.md). 
Please check this.

**Comment by dgmstuart** [comment]
Excellent - thankyou for a great response. The gem is now working for me
